### ISSUE TITLE
Bubblegum Backfill Force Option

### ISSUE THREAD

**Issue by kespinola** [rpcpool/digital-asset-rpc-infrastructure#147]
## Goal
Do a complete reindex ignoring cl_audits_v2 so trees are backfilled from the first transaction in order to current seq.

## Requirements
- Add `force` flag that causes the backfiller to skip checking gaps.

**Comment by kevinrodriguez-io** [comment]
Taking this as a priority

**Comment by kevinrodriguez-io** [comment]
Solved in #148
